apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ibp-setup-test
spec:
  params:
    - name: api_endpoint
      description: ibp console address
    - name: api_authtype
      description: ibmcloud (for IBP Sass) or basic (for IBP SW)
    - name: api_key
      description: api key for IBP SaaS or password for IBP SW
  workspaces:
    - name: source
      description: The git repo
  steps:
    - name: setup-ibp
      workingDir: $(workspaces.source.path)
      image: ibmapblockchain/ibp-ansible:0.1
      script: |
        #!/bin/bash
        # copying dummy vars for testing
        cp -rv tekton/vars/*.yaml /vars/
        # putting env var into /vars/api.yaml
        cat <<EOF > ./vars/api.yaml
        # This is manually generated api.yaml from env vars
        api_endpoint: $(params.api_endpoint)
        api_authtype: $(params.api_authtype)
        api_key: $(params.api_key)
        EOF
        # log out for debugging
        cat vars/api.yaml

        ./scripts/network.sh up
        ./scripts/network.sh down
