- name: Create folders
  hosts: localhost
  vars_files:
    - vars/common.yaml
  tasks:
    - name: Create config, connection profile, wallet folder
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ channel_config_path }}"
        - "{{ connection_profile_path }}"
        - "{{ wallet_path }}"
        - "{{ components_path }}"
