---
- name: Create Peer Organization
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/organizations.yaml
  vars:
    # org_name: org1
    org: "{{ vars['peer_organizations'][org_name] }}"
    org_config_file: "{{ playbook_dir }}/vars/organizations.yaml"
  tasks:
    - name: Create certificate authority
      ibm.blockchain_platform.certificate_authority:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        name: "{{ org.ca.name }}"
        zone: "{{ org.ca.zone | default(omit) }}"
        config_override:
          ca:
            registry:
              maxenrollments: -1
              identities:
                - name: "{{ org.ca.admin_enrollment_id }}"
                  pass: "{{ org.ca.admin_enrollment_secret }}"
                  type: client
                  maxenrollments: -1
                  attrs:
                    hf.Registrar.Roles: "*"
                    hf.Registrar.DelegateRoles: "*"
                    hf.Revoker: true
                    hf.IntermediateCA: true
                    hf.GenCRL: true
                    hf.Registrar.Attributes: "*"
                    hf.AffiliationMgr: true
        resources:
          ca:
            requests:
              cpu: "{{ org.ca.resource.vcpu | default('100m') }}"
              memory: "{{ org.ca.resource.memory | default('200M') }}"
        storage:
          ca:
            size: "{{ org.ca.resource.storage | default('20Gi') }}"
        wait_timeout: "{{ wait_timeout | default(900) }}"

    - name: Enroll CA admin
      ibm.blockchain_platform.enrolled_identity:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        certificate_authority: "{{ org.ca.name }}"
        name: "{{ org.ca.admin_name }}"
        enrollment_id: "{{ org.ca.admin_enrollment_id }}"
        enrollment_secret: "{{ org.ca.admin_enrollment_secret }}"
        path: "{{ wallet_path }}/{{ org.ca.admin_name }}.json"

    - name: Register org admin, peers and monitoring user
      ibm.blockchain_platform.registered_identity:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        certificate_authority: "{{ org.ca.name }}"
        registrar: "{{ wallet_path }}/{{ org.ca.admin_name }}.json"
        enrollment_id: "{{ item.enrollment_id }}"
        enrollment_secret: "{{ item.enrollment_secret }}"
        type: "{{ item.type }}"
      loop: "{{ org.ca.id_list }}"

    - name: Enroll the org admin
      ibm.blockchain_platform.enrolled_identity:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        certificate_authority: "{{ org.ca.name }}"
        name: "{{ org.msp.admin }}"
        enrollment_id: "{{ msp_admin_info[0].enrollment_id }}"
        enrollment_secret: "{{ msp_admin_info[0].enrollment_secret }}"
        path: "{{ wallet_path }}/{{ org.msp.admin }}.json"
      vars:
        msp_admin_info: "{{ org.ca.id_list | selectattr('name', 'equalto', org.msp.admin) | list }}"
      register: org_admin

    - name: Create organization
      ibm.blockchain_platform.organization:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        name: "{{ org.msp.name }}"
        msp_id: "{{ org.msp.id }}"
        certificate_authority: "{{ org.ca.name }}"
        registrar: "{{ wallet_path }}/{{ org.ca.admin_name }}.json"
        admins:
          - "{{ org_admin.enrolled_identity.cert }}"

    - shell: yq r {{ org_config_file }} 'peer_organizations.{{org_name}}.peers[*].name'
      register: peer_list_output
    - set_fact:
        peer_list: "{{ peer_list_output.stdout_lines }}"

    - name: Construct peer complete information list
      set_fact:
        # Merge information in org.peers and org.ca.id_list
        peer_complete_info_list: "{{ peer_complete_info_list | default([]) + [org.peers | selectattr('name','equalto', item) | first | combine(org.ca.id_list | selectattr('name','equalto', item) | first)] }}"
      loop: "{{ peer_list }}"

    - name: Create peer(s)
      ibm.blockchain_platform.peer:
        state: "{{ state }}"
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        name: "{{ item.name }}"
        msp_id: "{{ org.msp.id }}"
        state_db: "{{ item.state_db }}"
        zone: "{{ item.zone | default(omit) }}"
        version: "{{ item.version | default('1.4.7-0')}}"
        certificate_authority: "{{ org.ca.name }}"
        enrollment_id: "{{ item.enrollment_id }}"
        enrollment_secret: "{{ item.enrollment_secret }}"
        admins:
          - "{{ org_admin.enrolled_identity.cert }}"
        resources:
          peer:
            requests:
              cpu: "{{ item.resource.peer.vcpu | default('300m') }}"
              memory: "{{ item.resource.peer.memory | default('300M') }}"
          proxy:
            requests:
              cpu: "{{ item.resource.proxy.vcpu | default('100m') }}"
              memory: "{{ item.resource.proxy.memory | default('200M') }}"
          couchdb:
            requests:
              cpu: "{{ item.resource.couchdb.vcpu | default('300m') }}"
              memory: "{{ item.resource.couchdb.memory | default('300M') }}"
          chaincodelauncher: #only applicable for HF 2.X
            requests:
              cpu: "{{ item.resource.chaincodelauncher.vcpu | default('200m') }}"
              memory: "{{ item.resource.chaincodelauncher.memory | default('400M') }}"
          dind: #only applicable for HF 1.4.X
            requests:
              cpu: "{{ item.resource.dind.vcpu | default('500m') }}"
              memory: "{{ item.resource.dind.memory | default('500M') }}"
        storage:
          peer:
            size: "{{ item.resource.peer.storage | default('100Gi') }}"
          statedb:
            size: "{{ item.resource.couchdb.storage | default('100Gi') }}"
        wait_timeout: "{{ wait_timeout | default(1800) }}"
      loop: "{{ peer_complete_info_list }}"
  
    - name: Retrieve MSP
      ibm.blockchain_platform.organization_info:
        api_endpoint: "{{ org.console.api_endpoint }}"
        api_authtype: "{{ org.console.api_authtype }}"
        api_key: "{{ org.console.api_key | default(omit) }}"
        api_secret: "{{ org.console.api_secret | default(omit)}}"
        name: "{{ org.msp.name }}"
      register: result

    - name: Store MSP into a file
      copy:
        content: "{{ result.organization | to_nice_json }}"
        dest: "{{ components_path }}/{{ org.msp.name }}_MSP.json"
