#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Join the channel
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
    - vars/channels.yaml
  vars:
    # os_org_name: os
    # peer_org_name: org1
    # channel_name: samplechannel1
    os_org: "{{ vars['ordering_organization'][os_org_name] }}"
    peer_org: "{{ vars['peer_organizations'][peer_org_name] }}"
    peer_org_msp_admin: "{{ playbook_dir }}/{{ wallet_path }}/{{ peer_org.msp.admin }}.json"
  tasks:
    - name: Fetch the genesis block for the channel
      ibm.blockchain_platform.channel_block:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        operation: fetch
        ordering_service: "{{ os_org.orderer.name }}"
        identity: "{{ peer_org_msp_admin }}"
        msp_id: "{{ peer_org.msp.id }}"
        name: "{{ channel_name }}"
        target: "0"
        path: "{{ channel_config_path }}/{{ channel_name }}_genesis_block.bin"

    - name: Join the peer(s) to the channel
      ibm.blockchain_platform.peer_channel:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        operation: join
        peer: "{{ item }}"
        identity: "{{ peer_org_msp_admin }}"
        msp_id: "{{ peer_org.msp.id }}"
        path: "{{ channel_config_path }}/{{ channel_name }}_genesis_block.bin"
      with_items: "{{ peer_org.peers | map(attribute='name') | list }}"
