#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install chaincode
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
  vars:
    # peer_org_name: org1
    # cc_path: chaincode/marbles@v1.cds
    peer_org: "{{ vars['peer_organizations'][peer_org_name] }}"
    peer_org_msp_admin: "{{ playbook_dir }}/{{ wallet_path }}/{{ peer_org.msp.admin }}.json"
    cc: "{{ vars['chaincodes'][cc_name] }}"
  tasks:
    - name: Install the chaincode on the peer
      ibm.blockchain_platform.installed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ item }}"
        identity: "{{ peer_org_msp_admin }}"
        msp_id: "{{ peer_org.msp.id }}"
        path: "{{ cc_path }}"
      with_items: "{{ peer_org.peers | map(attribute='name') | list }}"
