#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install chaincode
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
  vars:
    # peer_org_name: org1 # load this using --extra-vars "peer_org_name=org1"
    # cc_path: chaincode/marbles@v1.cds # load this using --extra-vars "cc_path=chaincode/marbles@v1.cds"
    org_msp_admin: "{{ vars['peer_organizations'][peer_org_name]['msp']['admin'] }}{{ identity_prefix }}.json"
    org_msp_id: "{{ vars['peer_organizations'][peer_org_name]['msp']['id'] }}"
    peers: "{{ vars['peer_organizations'][peer_org_name]['peers'] }}"
    smart_contract_package: "{{ playbook_dir }}/{{ cc_path }}"
  tasks:
    - name: Install the chaincode on the peer
      ibm.blockchain_platform.installed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ item }}"
        identity: "{{ org_msp_admin }}"
        msp_id: "{{ org_msp_id }}"
        path: "{{ smart_contract_package }}"
      with_items: "{{ peers }}"
