#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Instantiate chaincode
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
    - vars/chaincodes.yaml
  vars:
    # peer_org_name: org1
    # cc_name: marbles
    # channel_name: samplechannel1
    peer_org: "{{ vars['peer_organizations'][peer_org_name] }}"
    peer_org_msp_admin: "{{ playbook_dir }}/{{ wallet_path }}/{{ peer_org.msp.admin }}.json"
    peer_list: "{{ peer_org.peers | map(attribute='name') | list }}" 
    cc: "{{ vars['chaincodes'][cc_name] }}"
  tasks:
    - name: Instantiate the chaincode on the channel
      ibm.blockchain_platform.instantiated_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ peer_list[0] }}" # harcoded to the first peer
        identity: "{{ peer_org_msp_admin }}"
        msp_id: "{{ peer_org.msp.id }}"
        channel: "{{ channel_name }}"
        name: "{{ cc_name }}"
        constructor:
          function: "{{ cc_init_func | default(omit) }}"
          args: "{{ cc_init_args | default(omit) }}"
        version: "{{ cc_ver }}"
        endorsement_policy: "{{ cc_endorsement_policy | default(omit) }}"
        collections_config: "{{ cc_collections_config | default(omit) }}"
      
