#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create connection profile
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
  vars:
    # peer_org_name: org1
    ordering_service_name: "{{ vars['ordering_organization'][os_org_name]['orderer']['name'] }}"
    org_msp_admin: "{{ vars['peer_organizations'][peer_org_name]['msp']['admin'] }}{{ identity_prefix }}.json"
    org_msp_id: "{{ vars['peer_organizations'][peer_org_name]['msp']['id'] }}"
    org_msp_name: "{{ vars['peer_organizations'][peer_org_name]['msp']['name'] }}"
    org_ca_name: "{{ vars['peer_organizations'][peer_org_name]['ca']['name'] }}"
    peers: "{{ vars['peer_organizations'][peer_org_name]['peers'] }}"  
  tasks:
    - name: Create a connection profile
      ibm.blockchain_platform.connection_profile:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        name: "{{ org_msp_name }} Gateway"
        path: "{{ connection_profile_path }}/{{ org_msp_name }} Gateway.json"
        organization: "{{ org_msp_name }}"
        certificate_authority: "{{ org_ca_name }}"
        peers: "{{ peers }}"
