#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create connection profile
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/api.yaml
    - vars/organizations.yaml
  vars:
    # peer_org_name: org1
    peer_org: "{{ vars['peer_organizations'][peer_org_name] }}"
  tasks:
    - name: Create a connection profile
      ibm.blockchain_platform.connection_profile:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        name: "{{  peer_org.msp.name }} Gateway"
        path: "{{ connection_profile_path }}/{{ peer_org.msp.name }} Gateway.json"
        organization: "{{ peer_org.msp.name }}"
        certificate_authority: "{{ peer_org.ca.name }}"
        peers: "{{ peer_org.peers | map(attribute='name') | list }}" 
