#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Instantiate chaincode
  hosts: localhost
  vars_files:
    - vars/common.yaml
    - vars/organizations.yaml
    - vars/channels.yaml
  vars:
    # peer_org_name: org1
    # cc_name: marbles
    # channel_name: samplechannel1
    peer_org: "{{ vars['peer_organizations'][peer_org_name] }}"
    peer_org_msp_admin: "{{ wallet_path }}/{{ peer_org.msp.admin }}.json"
    peer_list: "{{ peer_org.peers | map(attribute='name') | list }}"
    cc: "{{ vars['channels'][channel_name]['chaincodes'][cc_name] }}"
  tasks:
    - name: Instantiate the chaincode on the channel
      ibm.blockchain_platform.instantiated_chaincode:
        api_endpoint: "{{ peer_org.console.api_endpoint }}"
        api_authtype: "{{ peer_org.console.api_authtype }}"
        api_key: "{{ peer_org.console.api_key }}"
        api_secret: "{{ peer_org.console.api_secret | default(omit) }}"
        peer: "{{ peer_list[0] }}" # harcoded to the first peer
        identity: "{{ peer_org_msp_admin }}"
        msp_id: "{{ peer_org.msp.id }}"
        channel: "{{ channel_name }}"
        name: "{{ cc_name }}"
        constructor:
          function: "{{ cc.constructor.function | default(omit) }}"
          args: "{{ cc.constructor.args | default(omit) }}"
        version: "{{ cc.version }}"
        endorsement_policy: "{{ cc.endorsement_policy | default(omit) }}"
        collections_config: "{{ cc.collections_config | default(omit) }}"
