---
- name: Delete folders
  hosts: localhost
  vars_files:
    - vars/common.yaml
  tasks:
    - name: Delete folders
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ channel_config_path }}"
        - "{{ connection_profile_path }}"
        - "{{ wallet_path }}"
        - "{{ channel_policies_path }}"
        - "{{ bulk_import_path }}"
