---
- name: Zip identities to wallet
  hosts: localhost
  tasks:
    - name: Create Wallet folder
      file:
        path: "{{ playbook_dir }}/Wallet"
        state: directory
        mode: '0755'
    - name: Insert `identity` field and insert identity JSON files to Wallet folder
      shell: "cat '{{ item }}' | jq '. + {type: \"identity\"}' > '{{ playbook_dir }}/Wallet/{{ item | basename }}'"
      with_fileglob:
        - "{{ playbook_dir }}/*.json"
    - name: Create a zip archive of {{ playbook_dir }}/Wallet
      archive:
        path: "{{ playbook_dir }}/Wallet"
        format: zip
        dest: "{{ playbook_dir }}/Wallet.zip"