apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ibp-setup-test
spec:
  params:
    - name: api-endpoint
      description: ibp console address
    - name: api-authtype
      description: ibmcloud (for IBP Sass) or basic (for IBP SW)
    - name: api-key
      description: api key for IBP SaaS or password for IBP SW
  workspaces:
    - name: source
      description: The git repo
  steps:
    - name: setup-ibp
      workingDir: $(workspaces.source.path)
      image: ibmapblockchain/ibp-ansible:0.1
      script: |
        #!/bin/bash
        # copying dummy vars for testing
        cp -rv .tekton/vars/*.yaml vars/
        # putting env var into /vars/api.yaml
        cat <<EOF > ./vars/api.yaml
        # This is manually generated api.yaml from env vars
        api_endpoint: $(params.api-endpoint)
        api_authtype: $(params.api-authtype)
        api_key: $(params.api-key)
        EOF

        STATUS_CODE=0
        # set up ibp network and all components
        ./scripts/network.sh up
        if [ "$?" != 0 ]; then
        STATUS_CODE=1
        fi

        # tear everything down
        ./scripts/network.sh down
        exit "$STATUS_CODE"
